### ISSUE TITLE
The exe file in EXE folder can't run.

### ISSUE THREAD

**Issue by mo1shang** [vvvwo/Adaptively-Isotropic-Remeshing#1]
当我在win11系统上双击EXE文件夹下的exe文件，我遇到了错误，首先是缺少一些dll文件，在我下载dll文件之后，我遇到了这样的错误：应用程序无法正常启动（0x000007b）。请单击“确定”关闭应用程序
When I double-click the EXE file under the exe folder on win11 system, I encounter errors, first of all some dll files are missing, after I download the dll file, I encounter this error: the application does not start properly (0x000007b). Click OK to close the application

**Comment by mo1shang** [comment]
well, now the problem was addressed. I need to edit the start file under the EXE folder to specify the path of .obj file.

**Comment by lujunhao123** [comment]
> 好吧，现在问题得到了解决。我需要编辑 EXE 文件夹下的启动文件以指定.obj文件的路径。

Can you share the results of your success

**Comment by mo1shang** [comment]
![Image](https://github.com/user-attachments/assets/d59fe1d2-b5a8-4f3e-8160-37f5c3f5f556)
